### PR TITLE
update bignum, filing, overload FpX operators

### PR DESCRIPTION
**Pull request by iAmMichaelConnor**
Update to BigNum 0.4.1.
Filing.
Add overloaded operators. (Probably should've done this in a separate PR)

### CODE REVIEW

**Comment by iAmMichaelConnor** [comment]
Edit: whoops, sorry! I was meant to do this PR into my fork 😅

**Comment by ewynx** [comment]
That's awesome though! Totally up for that improvement

**Comment by iAmMichaelConnor** [comment]
I was going to work on an optimised pairing library (there are a few optimisations we have in mind), and then found your library which is a very clean implementation that we might build off, if that's ok? :)
Out of interest, I measured the constraint counts of `pairing` (using the example `main()` function that you suggest in your README), on your `master` branch, using Noir 0.35.0 and the associated version of `bb`, and I measured 3,210,945 versus your readme's quoted 2,580,893 constraints. Did I do something wrong, or is your measurement slightly out of date?
And when I updated both Noir and BigNum on my branch, the constraints have gone up to 3,951,488, and I'm trying to figure out which of Noir or BigNum caused this blowup.

**Comment by ewynx** [comment]
Absolutely, glad it can be of use!

I'll run the benchmark again and get back to you with the number

**Comment by ewynx** [comment]
Yes you are absolutely right about the gatecount @iAmMichaelConnor, I don't know what happened there. It is indeed 3.210.945. Will adjust in README

**Pull request closed without merging**
